name: Run Tests

on: [push]

jobs:
  pytest:
    strategy:
      matrix:
        python-version: ["3.9", "3.13"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: latest

      - name: Install the project dependencies
        run: poetry install

      - name: Run Tests
        run: poetry run pytest -v
